# Generated by Django 5.1.2 on 2024-11-14 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_remove_quote_tags_quote_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Automobile",
        ),
        migrations.AddField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                default = None,
                on_delete=django.db.models.deletion.CASCADE,
                to="quotes.user",
            ),
            preserve_default=False,
        ),
    ]
