# Generated by Django 5.1.2 on 2024-11-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_automobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="tags",
        ),
        migrations.AddField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(to="quotes.tag"),
        ),
    ]
